---
title       : Temperature Conversion
subtitle    : 
author      : Dave Moore
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---

## Purpose

Have you ever traveled to a place that expresses temperature in different units than you are accustomed to?  

I am from the United States where temperature is typically expressed in degrees Fahrenheit.  In most other countries that I have traveled to, temperature is expressed in degrees Celsius.  When traveling, I often do the temperature conversion in my head.  

This cutting-edge app will do the conversion for you!  It converts both from Celsius to Fahrenheit and from Fahrenheit to Celsius.

--- .class #id

## How to Use the App

1. Enter the temperature you want converted.
2. Enter the type of units that temperature is expressed in (c for Celsius and f for Fahrenheit).
3. Press submit.
4. The app will return the converted temperature (if you entered c for Celsius, it will return the Fahrenheit conversion and vice-versa)

It's that simple!

--- .class #id

## Converting Celsius to Fahrenheit

The secret behind this miracle app is in the formula below:

To convert from Celsius to Fahrenheit, perform the following calculation:

Fahrenheit = Celsius*9/5 + 32

---

## Converting Fahrenheit to Celsius

An equally profound secret is the following formula to convert Fahrenheit to Celsius:

Celsius = (Fahrenheit - 32)*5/9




